# -*- coding: utf-8 -*-
"""Trabalho_versao_Alda.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Lv9P_M7rR4z5nV1HNJWkziXk6B5G0Lr4

# **Grupo 3 — Tipo de residência, faltas e classificação final**
"""

print("Este trabalho é baseado no estudo Using data mining to predict secondary school student performance")
print("Onde o objetivo é identificar fatores que influenciam o sucesso ou insucesso dos alunos em Portugal e prever o seu desempenho escolar")
print("Para esta análise iremos estudar a disciplina de Matemática")

import pandas as pd
df = pd.read_csv("student-mat.csv", sep=";")

df.shape

df.describe()

df.isna().sum()

df.info()

df.head()

print("Neste trabalho iremos apenas focar na relação entre a variável categórica Residência e variáveis numéricas Faltas e Notas Finais")

df[['address', 'absences', 'G3']]

df["absences"].mean()

df["address"].mode()

df["G3"].min()

df["G3"].max()

df['absences'].std()

df["address"].value_counts()

variaveis_numericas = ["absences", "G3"]
df[variaveis_numericas].describe()

q1 = df["G3"].quantile(0.75)
q3 = df["G3"].quantile(0.90)
med = df.G3.median()

print("med", med)
print("Quantil10:", q1)
print("Quantil90:", q3)
print("Amplitude interquartil:", q3 - q1)

df["age"].describe()

df[variaveis_numericas].max() - df[variaveis_numericas].min()

print("Variâncias:")
print(df[variaveis_numericas].var())

print("\nDesvios padrão:")
print(df[variaveis_numericas].std())

import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd

df = pd.read_csv("student-mat.csv", sep=";")

categorical_variables = ["address", "absences"]

for col in categorical_variables:
    plt.figure(figsize=(6, 6))
    sns.countplot(data=df, x=col, palette='viridis', hue=col, legend=False)
    plt.title(f'Distribuição de {col}')
    plt.xlabel(col)
    plt.ylabel('Contagem')
    plt.xticks(rotation=45, ha='right')
    plt.grid(axis='y', linestyle='--', alpha=0.7)
    plt.tight_layout()
    plt.show()

import matplotlib.pyplot as plt
import pandas as pd

# Ler dataset
df = pd.read_csv("student-mat.csv", sep=";")

# Criar gráfico
plt.figure(figsize=(8,6))

plt.scatter(df['absences'], df['G3'])

# Títulos e labels
plt.title('Faltas vs Nota Final')
plt.xlabel('Faltas')
plt.ylabel('Nota Final (G3)')

# Grid
plt.grid(True)

# Mostrar gráfico
plt.show()

#usar este grafico
import matplotlib.pyplot as plt
import pandas as pd

# Ler dataset
df = pd.read_csv("student-mat.csv", sep=";")

# Contar alunos por residência
contagem = df['address'].value_counts()

# Criar gráfico de barras
plt.figure(figsize=(6,5))

plt.bar(contagem.index, contagem.values)

# Títulos
plt.title('Número de Alunos por Residência')
plt.xlabel('Residência')
plt.ylabel('Número de Alunos')

# Mostrar gráfico
plt.show()

#Resumo direto: o gráfico mostra que há muito mais alunos na categoria “U” do que na categoria “R”. A distribuição é claramente desigual, com a residência “U” sendo dominante.
#O que este gráfico de barras revela

#“U” tem mais de 300 alunos → é a residência mais comum.

#“R” tem cerca de 90 alunos → muito menos representada.

#A diferença entre as duas categorias é grande e evidente.

#O gráfico é unidimensional categórico, ideal para comparar frequências entre grupos.

#Interpretação

#A população estudantil está concentrada na categoria “U”.

#Pode indicar que a maioria dos alunos vive em áreas urbanas (se “U” = urbano) ou na escola (se “U” = internato), dependendo do contexto do dataset.

#A categoria “R” representa uma minoria significativa, mas ainda relevante.

import matplotlib.pyplot as plt
import pandas as pd

df = pd.read_csv("student-mat.csv", sep=";")

plt.figure(figsize=(6, 6))
plt.hist(df['absences'], bins=20, edgecolor='black')
plt.title('Distribuição da variável Faltas')
plt.xlabel('Faltas')
plt.ylabel('Nota Final')
plt.grid(axis='y', alpha=0.75)
plt.show()

#    A maioria dos estudantes tem pouquíssimas faltas — o primeiro intervalo tem quase 200 ocorrências.
#À medida que o número de faltas aumenta, a frequência cai de forma acentuada.
#A distribuição é assimétrica à direita (skewed right): muitos com poucas faltas, poucos com muitas faltas.
#Interpretação estatística Isto indica que faltas elevadas são raras. A variável “faltas” tem uma cauda longa, típica de comportamentos onde a maioria cumpre e poucos se desviam muito.

#usar este grafico
plt.hist(df['absences'], bins=20)
plt.title("Histograma das Faltas")

#**Resumo direto:** o gráfico mostra que a maioria das pessoas tem **poucas faltas** e que **faltas muito altas são raras**. É uma distribuição **assimétrica à direita** (muitos valores baixos, poucos valores altos).


## O que este **histograma** revela Concentração perto do zero:** a maior parte dos alunos tem entre **0 e 5 faltas**.
#**Cauda longa à direita:** existem alguns casos com muitas faltas (20, 30, 40, até ~70), mas são **poucos**.
# **Distribuição não é uniforme:** há um padrão claro de que **quanto maior o número de faltas, menor a frequência**.
# **Possível presença de outliers:** valores muito altos podem indicar **casos excepcionais**.


## 🧠 Interpretação estatística

#A variável **não é normal**; é **assimétrica positiva**.
# A média provavelmente é **maior que a mediana**, porque a cauda puxa a média para cima.
# A maior parte dos dados está concentrada no início do eixo X → **baixa variabilidade para a maioria**, mas **alta variabilidade nos casos extremos**.

---

## 🔍 O que podes concluir sobre o comportamento dos alunos

#A maioria falta pouco → comportamento geral **regular**.
#Há um pequeno grupo com faltas muito elevadas → pode indicar **problemas específicos**, como desmotivação, dificuldades pessoais ou risco de retenção.

import matplotlib.pyplot as plt

plt.figure(figsize=(8, 5))
plt.boxplot(df["absences"].dropna(), showfliers=True)
#plt.boxplot(df["absences"])
plt.title("Boxplot da variável absences")
plt.ylabel("Faltas")
plt.xticks([]) # Remove ticks no eixo dos xx
plt.show()

#usar este gráfico
import seaborn as sns
import matplotlib.pyplot as plt

plt.figure(figsize=(10, 6))
var = "address"
sns.boxplot(x=var, y='G3', data=df.dropna(subset=['G3', var]), showfliers=False)
plt.title('Boxplot das Notas Finais por Residência')
plt.xlabel('Tipo de Residência')
plt.ylabel('Nota Final (G3)')
plt.show()

#Este boxplot compara a nota final (G3) entre alunos de residência: U → urbana R → rural
#1. Mediana das notas A linha no centro da caixa representa a mediana. Em U, a mediana está perto de 11. Em R, está perto de 10.

#Isto indica que os alunos urbanos tendem a ter notas finais ligeiramente superiores.

#2.Dispersão das notas A altura da caixa mostra a variabilidade das notas. O grupo R parece ter uma dispersão um pouco maior.
#Isso significa que entre os alunos rurais existem diferenças maiores entre notas baixas e altas.
#3. Valores mínimos e máximos

#Os “bigodes” mostram os extremos normais.

#Em U, as notas variam aproximadamente entre 4 e 20.
#Em R, variam entre 0 e 19.
#O grupo rural apresenta casos de nota muito baixa (0), enquanto no urbano o mínimo é mais alto.

#4. Sobreposição das caixas

#As caixas sobrepõem-se bastante. Isso significa que: os dois grupos têm distribuições relativamente semelhantes;a diferença existe, mas não é muito forte.
#Conclusão geral O gráfico sugere que: alunos urbanos (U) têm desempenho final ligeiramente melhor; alunos rurais (R) apresentam maior variabilidade nas notas;
#a residência pode ter alguma influência no G3, mas não é uma diferença muito grande.#

#usar este grafico
import matplotlib.pyplot as plt
import seaborn as sns

plt.figure(figsize=(10, 6))
sns.scatterplot(x='absences', y='G3', data=df,
                hue='address',
                style='address',
                alpha=0.7
                )
plt.title('Scatterplot de Faltas vs. Nota Final por Residência')
plt.xlabel('Faltas')
plt.ylabel('Nota Final')
plt.grid(True, linestyle='--', alpha=0.7)
plt.legend(title='Residência')
plt.show()

#Este scatterplot mostra a relação entre: Faltas (absences) → eixo X Nota final (G3) → eixo Y Tipo de residência (address) azul = urbano (U) laranja = rural (R)

#1. Tendência negativa entre faltas e nota À medida que as faltas aumentam: as notas tendem a diminuir.Isto sugere uma correlação negativa: mais faltas → pior desempenho académico.
#2. Concentração principal dos alunos A maior parte dos pontos está: entre 0 e 15 faltas e notas entre 8 e 16

#Isso indica que a maioria dos alunos: tem relativamente poucas faltas; e notas médias/positivas.
#3. Muitos alunos com poucas faltas têm boas notas No lado esquerdo do gráfico: vemos vários alunos com: poucas faltas, e notas entre 14 e 20.

#Isso reforça a ideia de que assiduidade ajuda no desempenho.

#4. Alunos com muitas faltas tendem a ter notas baixas

#À direita do gráfico: aparecem alunos com 30, 40, 50 e até 75 faltas; quase todos têm notas mais baixas.

#Não aparecem notas muito altas associadas a muitas faltas.

#5. Comparação entre urbano (U) e rural (R) Os dois grupos estão bastante misturados.

#Isso significa que: o padrão entre faltas e nota é parecido nos dois tipos de residência; o tipo de residência não parece alterar muito a relação. 6. Existem exceções

#O gráfico também mostra alguns casos fora da tendência: alunos com poucas faltas mas notas baixas; alguns com faltas moderadas e notas razoáveis.

#Portanto, as faltas influenciam o desempenho, mas não explicam tudo.

#Conclusão geral O gráfico indica que: existe uma relação negativa entre faltas e nota final; alunos com menos faltas tendem a obter melhores resultados;
#o padrão é semelhante para alunos urbanos e rurais;
#a residência tem pouca influência comparada com o impacto das faltas.

#usar este grafico de barras
df["address"].value_counts(normalize  = False).plot(kind="bar", figsize=(8, 5))
plt.title("Faltas por Residência")
plt.xlabel("Residência")
plt.ylabel("Faltas")
plt.xticks(rotation=45, ha="right")
plt.tight_layout()
plt.show()

#A leitura essencial do gráfico é muito direta e forte: há uma diferença enorme no número de faltas entre as duas categorias de residência.
#O que o gráfico mostra A categoria U tem mais de 300 faltas. A categoria R tem cerca de 90 faltas.
#Ou seja, estudantes da residência U faltam aproximadamente 3 a 4 vezes mais do que os da residência R.
#Interpretação Existe uma desigualdade clara no comportamento de faltas entre os dois grupos.
#A residência U apresenta um nível de faltas muito superior, o que pode indicar: problemas de deslocação diferenças socioeconómicas
#menor acompanhamento maior desmotivação
#horários menos compatíveis ou qualquer outro fator contextual que valha a pena investigar

#usar este grafico
import pandas as pd
import matplotlib.pyplot as plt

# Contar categorias
contagem = df['address'].value_counts()

# Criar pie chart
plt.pie(contagem,
        labels=contagem.index,
        autopct='%1.1f%%')

plt.title('Distribuição de Tipo de Residência')
plt.axis('equal')
plt.show()

Os tópicos que acho que devemos abordar acho que em primeiro:
quantas pessoas tem casa urbana e quantas rural.
Depois a relação entre casa e as faltas x grafico de barras
a relação entre faltas e notas x grafico histograma
relação entre casa e notas
Relação entre Residencia Notas e Faltas x scatterplot

import matplotlib.pyplot as plt

# Valores no eixo X (número de faltas)
faltas = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10,
           11, 12, 13, 14, 15, 16, 17, 18,
           19, 20, 21, 22, 24, 25, 26, 28,
           30, 38, 40, 54, 56, 75]

# Frequência (contagem de alunos)
contagem = [115, 3, 65, 8, 53, 1, 31, 7, 22, 3,
            17, 3, 12, 3, 12, 3, 7, 1, 5, 1,
            4, 1, 3, 1, 1, 1, 1, 1, 1, 1,
            1, 1, 1]

# Criar figura
plt.figure(figsize=(10, 6))

# Gráfico de barras
plt.bar(faltas, contagem, color="#44235e")

# Título e labels
plt.title("Distribuição de absences", fontsize=14)
plt.ylabel("Contagem", fontsize=12)

# Mostrar grelha horizontal
plt.grid(axis='y', linestyle='--', alpha=0.7)

# Mostrar gráfico
plt.show()

"""interpretar os principais resultados obtidos; • responder à questão orientadora do seu tema; • apresentar uma conclusão breve, clara e fundamentada.

Interpretação:

Através da análise dos gráficos, foi possível identificar padrões relevantes no que respeita à zona de residência dos alunos, a quantidade de faltas registadas e o seu desempenho académico.

Os dados revelam que a maioria dos alunos se enquadra na categoria "U", enquanto a categoria "R" corresponde a uma porção bem menor do total de estudantes. Isto evidencia uma presença muito significativa de alunos da zona urbana.

No que diz respeito às faltas, constatou-se que a generalidade dos alunos tem poucas ausências, tipicamente situadas entre 0 e 5. Contudo, há um grupo reduzido que apresenta faltas em quantidade muito superior, originando uma distribuição enviesada para a direita. Estes casos excecionais podem estar vinculados a problemas no percurso escolar, falta de interesse ou maior vulnerabilidade ao insucesso académico.

Quando se compara a residência com a classificação final, verifica-se que os alunos da cidade obtêm notas um pouco melhores do que aqueles que vivem no campo. Mesmo assim, os padrões de distribuição são bastante próximos, sugerindo que a zona onde se reside não origina disparidades significativas no rendimento escolar. O grupo do interior apresenta uma dispersão maior nas notas e alguns casos isolados de classificações particularmente fracas.

O gráfico de dispersão confirmou ainda uma correlação inversa entre faltas e classificação final: quanto mais faltas um aluno tem, mais baixa tende a ser a sua nota. Este comportamento manifesta-se tanto entre os alunos urbanos como rurais, indicando que as faltas têm um peso superior em comparação com o efeito da localização geográfica.

Conclusão:

Pode concluir-se que o número de faltas é o fator que mais peso tem no desempenho académico dos alunos. Aqueles que faltam menos conseguem notas mais elevadas, ao passo que ausências frequentes se correlacionam com resultados mais insatisfatórios. A localização geográfica, urbana ou rural, produz apenas variações moderadas e representa um impacto reduzido quando se considera a importância das faltas para o sucesso académico.
"""